### ISSUE TITLE
Ethereum transaction signing issues

### ISSUE THREAD

**Issue by ThatSlyGuy** [MelbourneDeveloper/Trezor.Net#10]
In the current state of the Trezor.Net library, there are some very strange results when attempting to sign an Ethereum transaction. 

This is the code I am using to try and sign a transaction:

```c#
[TestMethod]
public async Task SignEthereumTransaction()
{
    await GetAndInitialize();

    //Note: these are not reasonable values. They should not be used for a transaction. Looking for a better example here...
    var txMessage = new EthereumSignTx
    {
        Nonce = 0.ToHexBytes(),
        GasPrice = 1000000000.ToHexBytes(),
        GasLimit = 21000.ToHexBytes(),
        To = "689c56aef474df92d44a1b70850f808488f9769c".ToHexBytes(),
        Value = 100000000000000.ToHexBytes(),
        AddressNs = ManagerHelpers.GetAddressPath(false, 0, false, 0, 60),
        ChainId = 4
    };

    var transaction = await TrezorManager.SendMessageAsync<EthereumTxRequest, EthereumSignTx>(txMessage);

    Assert.AreEqual(transaction.SignatureR.Length, 32);
    Assert.AreEqual(transaction.SignatureS.Length, 32);
}
```

The transaction signing goes wrong in a few different areas. 

Firstly, when attempting to sign a transaction on the Rinkeby network through https://mycrypto.com, we can see the output on our device as something related to the following:

> Send 1.0 tEth to 0x689c56aef474df92d44a1b70850f808488f9769c?

After confirming this, we get the next message:

> Really send 1.0 tEth paying up to 0.000021 tEth for gas?

When attempting to sign the same transaction through Trezor.Net, we get the something similar to the following:

> Send message to 0x689c56aef474df92d44a1b70850f808488f97600

After confirming this, we'll get this next message: 

> Really send message paying up to 0.000021 UNKN for gas?

The first bit of strange behavior is with the fact that even though we are sending an `EthereumSignTx`, the Trezor is interpreting it as signing a message through `EthereumSignMessage`. The text 'Send Message' should only really appear if we are signing a message through `EthereumSignMessage`.

The second bit of strange behavior is seen in the actual address. The address where the message is being sent to the device in its entirety it seems. Sometimes only the last few characters of the address will be '0', sometimes it will be many more. 

The last bit of strange behavior is that the Trezor doesn't seem to recognize the ChainCode that we have entered, and therefore states we are trying pay the transaction fee with currency UNKN.

I'm not really sure where the issue lies in all of this, but clearly something is up.

**Comment by MelbourneDeveloper** [comment]
@ThatSlyGuy have you looked at #9 ?

I believe that 9# has been fixed.

**Comment by MelbourneDeveloper** [comment]
This stuff does seem strange. It seems to be doing the same thing with the latest code. It is is sending the EthereumSignTx message which is 58:

![image](https://user-images.githubusercontent.com/16697547/46997584-c6b11500-d16b-11e8-9415-675c4e9a2eb2.png)

**Comment by MelbourneDeveloper** [comment]
It's possible that there are still bugs in the reading/writing to the device.

**Comment by juanfranblanco** [comment]
@ThatSlyGuy @MelbourneDeveloper 
Hi I have not managed to sign a transaction successfully yet, banging my head on combinations. Well I do sign stuff, but  it is incorrect the response in comparison with Nethereum, so some of the parameters are not passed correctly.

Signing messages work, not transactions :) I moved to messages to have a simple test case to start with. 

This is message signing using Nethereum

```csharp
 var message = new EthereumSignMessage
                        {
                            AddressNs = KeyPath.Parse("m/44'/60'/0'/0/0").Indexes,
                            Message = Encoding.UTF8.GetBytes("Hello").ToHex().ToHexBytes()
                        };

                        var messageSignature = await trezorManager.SendMessageAsync<EthereumMessageSignature, EthereumSignMessage>(message);

                        //Same as first address 
                        Console.WriteLine(ToHex(messageSignature.Address));

                        var signer = new Nethereum.Signer.EthereumMessageSigner();
                        var messageSignature2 = signer.EncodeUTF8AndSign("Hello", new EthECKey(
                            "0x2e14c29aaecd1b7c681154d41f50c4bb8b6e4299a431960ed9e860e39cae6d29"));

```

And this is where I am with transaction signing, GasLimit is recognised and address correctly, from the response, but it does not recognise the value. 

```csharp
  var txMessage = new EthereumSignTx
                        {
                            Nonce = 10.ToBytesForRLPEncoding().ToHex().ToHexBytes(),
                            GasPrice = 10.ToBytesForRLPEncoding().ToHex().ToHexBytes(),
                            GasLimit = 21000.ToBytesForRLPEncoding().ToHex().ToHexBytes(),
                            To = "689c56aef474df92d44a1b70850f808488f9769c".ToHexBytes(),
                            Value = BigInteger.Parse("10000000000000000000").ToBytesForRLPEncoding().ToHex().ToHexBytes(),
                            AddressNs = KeyPath.Parse("m/44'/60'/0'/0/0").Indexes,
                            //ChainId = 1
                        };
                        var transaction = await trezorManager.SendMessageAsync<EthereumTxRequest, EthereumSignTx>(txMessage);

```

**Comment by MelbourneDeveloper** [comment]
@juanfranblanco have you debugged the helper methods for ToHex and ToHexBytes etc? I'm not 100% sure that they're correct. If so...

Are you up for doing a test with the Trezor python library ? That would determine if the problem is in the library or in the parameters being passed. If the input is the same and the output is different, it probably means there is a bug in my library and I can take it from there.

**Comment by juanfranblanco** [comment]
@MelbourneDeveloper yes that was the next step.. the ToHex() is Nethereum the ToHexBytes() is yours but only for strings, on a documentation I read the need to remove the 0x and use hex strings.. hence GasLimit is recognised. I have to stop this for a while as it was lots of trying and error. But yeah ToHexBytes for a string seem to work correctly, based on the message, GasLimit and the Address.

**Comment by juanfranblanco** [comment]
Although it might be something with the Transaction Type, that was my other thought.

**Comment by MelbourneDeveloper** [comment]
@juanfranblanco @ThatSlyGuy the problem is pretty clear. On a basic level, the To address is completely wrong. I'm getting the same result with KeepKey It could be that the address is being sent to the device incorrectly, or it could be that the code is reading it incorrectly from the device. 

There's enough information here for me to investigate.

**Comment by juanfranblanco** [comment]
I don't have a problem with the To address (check my code) but it appears to sign message, so it might the transaction type. If you try really hard you will see the address here "689c56aef474df92d44a1b70850f808488f9769c" 
![image](https://user-images.githubusercontent.com/562371/47076131-edb42900-d1f5-11e8-965a-d4f678a93a91.png)

also check the Gwei here 
![image](https://user-images.githubusercontent.com/562371/47076321-5b605500-d1f6-11e8-9744-d3c84e96d15b.png)

**Comment by juanfranblanco** [comment]
Here is the full program, it is using the "old" TrezorManager https://github.com/juanfranblanco/Trezor.Net/blob/master/src/Trezor.Net.Sample/Program.cs

**Comment by juanfranblanco** [comment]
Ok further analysis https://github.com/trezor/trezor-mcu/blob/master/firmware/ethereum.c#L267-L268 the Value is send as 0 hence we have "message". The txn type is for WanChain so ignore that.

**Comment by MelbourneDeveloper** [comment]
@juanfranblanco thanks! Actually, I might have found the problem. I will get back to you soon.

**Comment by MelbourneDeveloper** [comment]
@juanfranblanco 
Can you try a pull from branch Issue10? I believe this has fixed @ThatSlyGuy 's problem. It may fix yours.

**Comment by juanfranblanco** [comment]
Sure

**Comment by MelbourneDeveloper** [comment]
@juanfranblanco I have added the unit test SignEthereumTransaction2 to master/Issues10 which is from your sample app. You can get it by doing a pull. Am I right in understanding that the problem is the Gas limit is coming up as 210000, and the currency is saying UNK?

**Comment by MelbourneDeveloper** [comment]
What do you expect this test to display on the Trezor?

**Comment by juanfranblanco** [comment]
Correct that is where we are now, although your fix has allowed to see the Value

**Comment by juanfranblanco** [comment]
It should be 21000 and 10 Ether, let me recreate in MEW and post some shots.

**Comment by MelbourneDeveloper** [comment]
Unfortunately, I have to call it a night. But, I can see that there is an issue. I think I have some ideas about what is happening. The Issue10 branch is one step closer. I think I'll be able to fix it tomorrow.

**Comment by MelbourneDeveloper** [comment]
@ThatSlyGuy  can you see if your issues are any closer with the Issue10 branch?

**Comment by juanfranblanco** [comment]
Have a great sleep, yes that branch fixed reading the Value so that is a great start, I don't get the extra zero of the GasLimit.

**Comment by juanfranblanco** [comment]
Ok re-reading the description it is the total Wei Price to it is 21k * 10 hence the 210000, so that is correct. I have checked the signatures and everything is fine. 


Also the simplified test case is here, just use Nethereum extensions for this.
```csharp

                        var txMessage = new EthereumSignTx
                        {
                            Nonce = 10.ToBytesForRLPEncoding(),
                            GasPrice = 10.ToBytesForRLPEncoding(),
                            GasLimit = 21000.ToBytesForRLPEncoding(),
                            To = "689c56aef474df92d44a1b70850f808488f9769c".HexToByteArray(),
                            Value = BigInteger.Parse("10000000000000000000").ToBytesForRLPEncoding(),
                            AddressNs = KeyPath.Parse("m/44'/60'/0'/0/0").Indexes,
                        };


                        var trezorTransactionSignature = await trezorManager.SendMessageAsync<EthereumTxRequest, EthereumSignTx>(txMessage);

                        var transactionSigner = new TransactionSigner();
                        var nethereumSignature = transactionSigner.SignTransaction("0x2e14c29aaecd1b7c681154d41f50c4bb8b6e4299a431960ed9e860e39cae6d29",
                         "0x689c56aef474df92d44a1b70850f808488f9769c", BigInteger.Parse("10000000000000000000"), 10, 10, 21000);
                        var transactionRecovered = new Transaction(nethereumSignature.HexToByteArray());

                        Console.WriteLine("Trezor R: " + trezorTransactionSignature.SignatureR.ToHex());
                        Console.WriteLine("Nethereum R: " + transactionRecovered.Signature.R.ToHex());
                        Console.WriteLine("Trezor S:" + trezorTransactionSignature.SignatureS.ToHex());
                        Console.WriteLine("Nethereum S: " + transactionRecovered.Signature.S.ToHex());
                        Console.WriteLine("Trezor V:" + trezorTransactionSignature.SignatureV);
                        Console.WriteLine("Nethereum V: " + new BigInteger(transactionRecovered.Signature.V));
```

**Comment by juanfranblanco** [comment]
@MelbourneDeveloper  So the only issue is the currency UNK, the rest is correct and signing correctly.  Next thing is signing token transactions or big data transactions.

**Comment by juanfranblanco** [comment]
More tidying on the message signing side:
```csharp
 var message = new EthereumSignMessage
                        {
                            AddressNs = KeyPath.Parse("m/44'/60'/0'/0/0").Indexes,
                            Message = Encoding.UTF8.GetBytes("Hello")
                        };
```
Ill do some pull requests later

**Comment by ThatSlyGuy** [comment]
@MelbourneDeveloper This is great! Your changes made in the issue10 branch seemed to have completely fixed everything, thanks a lot! Everything seems to be correctly and consistently displayed to the Trezor. I haven't checked if the v/r/s return values are correct yet, but I will get around to that next.

@juanfranblanco The UNKN thing is just a result of not including the ChainId in the `EthereumSignTx` initialization. If the ChainId is set to 1, then the Trezor displays ETH as the currency. If I set the ChainId to 4 (rinkeby), then the Trezor displays tETH. When no ChainId is included, it is not serialized, which makes the currency type appear as UNKN.

```c#
        [TestMethod]
        public async Task SignEthereumTransaction2()
        {
            await GetAndInitialize();

            var txMessage = new EthereumSignTx
            {
                Nonce = 10.ToBytesForRLPEncoding().ToHex().ToHexBytes(),
                GasPrice = 1000000000.ToBytesForRLPEncoding().ToHex().ToHexBytes(),
                GasLimit = 21000.ToBytesForRLPEncoding().ToHex().ToHexBytes(),
                To = "689c56aef474df92d44a1b70850f808488f9769c".ToHexBytes(),
                Value = BigInteger.Parse("10000000000000000000").ToBytesForRLPEncoding().ToHex().ToHexBytes(),
                AddressNs = KeyPath.Parse("m/44'/60'/0'/0/0").Indexes,
                ChainId = 1
            };
            var transaction = await TrezorManager.SendMessageAsync<EthereumTxRequest, EthereumSignTx>(txMessage);

            Assert.AreEqual(transaction.SignatureR.Length, 32);
            Assert.AreEqual(transaction.SignatureS.Length, 32);
        }
```

**Comment by juanfranblanco** [comment]
Cool the ChainId makes different types of Ether. 
On a similar fashion there is a registry of token addresses, if the address match the amount of tokens will be transferred.

**Comment by juanfranblanco** [comment]
Hopefully there are no more Java arrays ;)

**Comment by MelbourneDeveloper** [comment]
Great! 

The whole area of code needs to be rewritten. I only wrote it in one weekend. It can also be performance optimized. It was a literal translation from Java and I took shortcuts because I didn't understand Java too well. When I have time, I will clean this up and make it more readable.

**Comment by MelbourneDeveloper** [comment]
I have merged the fix in to master and will do a NuGet release.

@ThatSlyGuy @juanfranblanco so transactions are all good now? I can close these issues?

**Comment by ThatSlyGuy** [comment]
@MelbourneDeveloper I can definitely do that. I'm going to close this issue now that everything seems good. I'll reopen it or create a new one if any other problems arise.

**Comment by juanfranblanco** [comment]
All ok on my side, see also the final tests for Message Signing, Ether Transaction and Token Transaction. I need to do further checks on 155 signatures and big data elements. But I don't think it will be an issue. Next step to integrate in Nethereum like ledger :) :)

**Comment by MelbourneDeveloper** [comment]
@juanfranblanco @ThatSlyGuy incidentally, transaction signing now works on KeepKey (KeepKey.Net). It's basically all the same code.
