### ISSUE TITLE
Abstracting HID transport

### ISSUE THREAD

**Issue by NicolasDorier** [MelbourneDeveloper/Trezor.Net#2]
It would be nice if `TrezorManager` did not depend on `IHidDevice`, but by a similar class than Ledger API (similar to `ILedgerTransport`)

I would like to use this with my custom made transport for BTCPay. (Where the browser is connected to Trezor, and I want to pilot it from my backend via websocket)

**Comment by MelbourneDeveloper** [comment]
Good call. Sorry it took so long to see this. I don't seem to always get Github notifications.

Actually, I want to do exactly the same thing. I want to do it for iPhone support. 

Does this sound like what you are talking about?
https://github.com/trezor/trezor-mcu/issues/362

@NicolasDorier , I would like to create a Trezor server that will serve up the connection over REST. I was thinking of going even a step further and implementing a generic USB service. I would probably do it with ASP.NET Core. If done properly it could serve up either Ledger, or Trezor connection. It would really just be an implementation of a Hid.Net IHidDevice even though it doesn't actually communicate over USB.

**Comment by MelbourneDeveloper** [comment]
@nicolasdorier come to think of it, couldn't you just implement IHidDevice in your transport? If you do that, you can just pass it in to the TrezorManager constructor.

**Comment by NicolasDorier** [comment]
It might work. I need to try. Yeah, in BTCPay I created a bridge websocket <-> U2F which allow me to control a Ledger Wallet from server side. Very handy, and it was not so complex.

**Comment by MelbourneDeveloper** [comment]
If you let me know of anything that is specifically stopping you from doing that, I can change it.

**Comment by MelbourneDeveloper** [comment]
The answer is that Hid.Net is mainly just an interface so any kind of transport can be used. If there's a specific problem, I'm happy to look at it separately.
