### ISSUE TITLE
Ethereum message signature V issue

### ISSUE THREAD

**Issue by juanfranblanco** [MelbourneDeveloper/Trezor.Net#9]
Just for reference I have opened this issue https://github.com/trezor/trezor-mcu/issues/418

**Comment by MelbourneDeveloper** [comment]
You mean this one here, or both?

![image](https://user-images.githubusercontent.com/16697547/46857733-547fbe00-ce55-11e8-9bcf-cec570b40a90.png)

**Comment by MelbourneDeveloper** [comment]
This is confusing because in Java the array is indexed differently I think,

**Comment by juanfranblanco** [comment]
Yes that one :)

**Comment by juanfranblanco** [comment]
Yes that was the plan, I am trying to fix transactions at the moment. The signature is not correct.

**Comment by MelbourneDeveloper** [comment]
I'm just testing on Android and will check in the fix.

**Comment by MelbourneDeveloper** [comment]
The fix is in this NuGet:
https://www.nuget.org/packages/Trezor.Net/2.2.0

I can see why it went wrong now. It was a copy pasta mistake.

**Comment by MelbourneDeveloper** [comment]
Let me know if this fixes it for you.

**Comment by juanfranblanco** [comment]
Oh I am working on the Trezor.Net source, so I can debug and tinker :)

**Comment by MelbourneDeveloper** [comment]
No problem. It's committed in master.

**Comment by MelbourneDeveloper** [comment]
Btw sorry about the slow response. I never get notifications about new issues. Best to email me if something is wrong.

**Comment by juanfranblanco** [comment]
ha ha it happens to me the same, and monitoring so many repos is a nightmare.. gitter is my main point of contact if I am not in the zone :)

**Comment by MelbourneDeveloper** [comment]
@juanfranblanco this fix has actually solved a problem in the KeepKey library which is based on Trezor.Net. So, thanks. Can this ticket be closed now? Do you suspect there are other issues in reading and writing data to the Trezor? Have you seen #10 ?

**Comment by juanfranblanco** [comment]
Yes this is all working now :)
